version: "3.1"

services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "3306:3306"
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - .:/opt/pcm_bot
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    links:
      - db
    ports:
      - "9909:9909"
