version: "3.1"

services:
  db:
    build:
      context: .
      dockerfile: .docker/db.Dockerfile
    ports:
      - "3306:3306"
  php:
    build:
      context: .
      dockerfile: .docker/php.Dockerfile
    volumes:
      - .:/opt/pcm_bot
    links:
      - db
    ports:
      - "9000:9000"
